# Generated by Django 3.0.5 on 2020-04-29 05:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nicname', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateTimeField(blank=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('education', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Un-Married', 'Un-Married')], default='Un-Married', max_length=50)),
                ('place_of_married', models.TextField(blank=True)),
                ('general_note', tinymce.models.HTMLField()),
                ('bio', tinymce.models.HTMLField()),
                ('fathers_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_name', to='website.PersonProfile')),
                ('mothers_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_name', to='website.PersonProfile')),
                ('spouse_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_name', to='website.PersonProfile')),
            ],
        ),
    ]
