# Generated by Django 3.0.5 on 2020-04-29 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_personprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='general_note',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
