# Generated by Django 3.0.5 on 2020-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200429_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
