# Generated by Django 3.0.5 on 2020-04-29 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_personprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='website.PersonProfile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='website.PersonProfile')),
            ],
        ),
    ]
