# Generated by Django 3.0.5 on 2020-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_personchildren'),
    ]

    operations = [
        migrations.AddField(
            model_name='personchildren',
            name='extra',
            field=models.TextField(blank=True),
        ),
    ]
