# Generated by Django 3.0.5 on 2020-04-29 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_personchildren_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personprofile',
            old_name='nicname',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='personchildren',
            name='extra',
        ),
    ]
