# Generated by Django 3.0.5 on 2020-04-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200429_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personchildren',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='website.PersonProfile'),
        ),
        migrations.AlterField(
            model_name='personchildren',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='website.PersonProfile'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='fathers_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_name', to='website.PersonProfile'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='mothers_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_name', to='website.PersonProfile'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='spouse_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_name', to='website.PersonProfile'),
        ),
    ]
