# Generated by Django 3.0.5 on 2020-04-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200429_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='person_pic')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='website.PersonProfile')),
            ],
        ),
    ]
