# Generated by Django 3.0.5 on 2020-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_personphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
